# Modified template from https://www.appveyor.com/docs/lang/nodejs-iojs

# Test against this version of Node.js
environment:
  nodejs_version: "0.10"

# Get the latest stable version of Node 0.STABLE.latest (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: npm install -g node-gyp
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
    # run tests
  - npm test

# Don't actually build.
build: off

